// <auto-generated />
using System;
using BootstrapDashboard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BootstrapDashboard.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20230905205533_MigracionLectoresConDBSeed")]
    partial class MigracionLectoresConDBSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BootstrapDashboard.Models.Genero", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("CategoryId");

                    b.ToTable("generos");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 199, DateTimeKind.Utc).AddTicks(8932),
                            Nombre = "Novela Policiaca",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 199, DateTimeKind.Utc).AddTicks(8938)
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3842),
                            Nombre = "Romántico",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3846)
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3847),
                            Nombre = "Erótico",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3848)
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3849),
                            Nombre = "Ficción",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3850)
                        },
                        new
                        {
                            CategoryId = 5,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3851),
                            Nombre = "Biografía",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3852)
                        },
                        new
                        {
                            CategoryId = 6,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3853),
                            Nombre = "Ensayo",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3853)
                        },
                        new
                        {
                            CategoryId = 7,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3854),
                            Nombre = "Poesía",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3855)
                        },
                        new
                        {
                            CategoryId = 8,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3856),
                            Nombre = "Clásicos Literarios",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3857)
                        },
                        new
                        {
                            CategoryId = 9,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3858),
                            Nombre = "Cómic y Libros Ilustrados",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3859)
                        },
                        new
                        {
                            CategoryId = 10,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3860),
                            Nombre = "Cuentos y Relatos",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3860)
                        },
                        new
                        {
                            CategoryId = 11,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3862),
                            Nombre = "Fantasía",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3862)
                        },
                        new
                        {
                            CategoryId = 12,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3864),
                            Nombre = "Humor",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3864)
                        },
                        new
                        {
                            CategoryId = 13,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3865),
                            Nombre = "Infantil",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3866)
                        },
                        new
                        {
                            CategoryId = 14,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3867),
                            Nombre = "Juvenil",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3867)
                        },
                        new
                        {
                            CategoryId = 15,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3868),
                            Nombre = "Novela Histórica",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3869)
                        },
                        new
                        {
                            CategoryId = 16,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3870),
                            Nombre = "Novela Negra y Policiaca",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3871)
                        },
                        new
                        {
                            CategoryId = 17,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3872),
                            Nombre = "Novela Romántica",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3872)
                        },
                        new
                        {
                            CategoryId = 18,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3873),
                            Nombre = "Terror y Thriller",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3874)
                        },
                        new
                        {
                            CategoryId = 19,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3874),
                            Nombre = "Arte",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3875)
                        },
                        new
                        {
                            CategoryId = 20,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3876),
                            Nombre = "Autoayuda",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3877)
                        },
                        new
                        {
                            CategoryId = 21,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3878),
                            Nombre = "Biografías y Autobiografías",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3878)
                        },
                        new
                        {
                            CategoryId = 22,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3879),
                            Nombre = "Cocina y Gastronomía",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3880)
                        },
                        new
                        {
                            CategoryId = 23,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3880),
                            Nombre = "Deportes",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3881)
                        },
                        new
                        {
                            CategoryId = 24,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3882),
                            Nombre = "Divulgación Científica",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3882)
                        },
                        new
                        {
                            CategoryId = 25,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3883),
                            Nombre = "Enciclopedias y Diccionarios",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3884)
                        },
                        new
                        {
                            CategoryId = 26,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3885),
                            Nombre = "Filosofía",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3886)
                        },
                        new
                        {
                            CategoryId = 27,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3887),
                            Nombre = "Historia",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3887)
                        },
                        new
                        {
                            CategoryId = 28,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3888),
                            Nombre = "Idiomas",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3889)
                        },
                        new
                        {
                            CategoryId = 29,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3890),
                            Nombre = "Libros de Texto",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3890)
                        },
                        new
                        {
                            CategoryId = 30,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3891),
                            Nombre = "Libros Técnicos",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3892)
                        },
                        new
                        {
                            CategoryId = 31,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3892),
                            Nombre = "Madres y Padres",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3893)
                        },
                        new
                        {
                            CategoryId = 32,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3894),
                            Nombre = "Negocios e Inversiones",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3894)
                        },
                        new
                        {
                            CategoryId = 33,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3895),
                            Nombre = "Religión",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3896)
                        },
                        new
                        {
                            CategoryId = 34,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3897),
                            Nombre = "Viajes",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3897)
                        },
                        new
                        {
                            CategoryId = 35,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3898),
                            Nombre = "Teatro y Dramático",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3899)
                        },
                        new
                        {
                            CategoryId = 36,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3900),
                            Nombre = "Lírico",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(3901)
                        });
                });

            modelBuilder.Entity("BootstrapDashboard.Models.Lector", b =>
                {
                    b.Property<int>("IdLector")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLector"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdLector");

                    b.ToTable("lector");

                    b.HasData(
                        new
                        {
                            IdLector = 1,
                            Apellidos = "Casanova Almanza",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2788),
                            Direccion = "Ourense, 25 43141 Vilallonga del Camp",
                            Email = "AnaiasCasanovaAlmanza@jourrapide.com",
                            Nombre = "Anaías",
                            Telefono = "783 962 738",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2791)
                        },
                        new
                        {
                            IdLector = 2,
                            Apellidos = "Castro Montoya",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2794),
                            Direccion = "Plaza Colón, 55 26100 Torrecilla en Cameros",
                            Email = "PericlesCastroMontoya@armyspy.com",
                            Nombre = "Pericles",
                            Telefono = "783 962 730",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2795)
                        },
                        new
                        {
                            IdLector = 3,
                            Apellidos = "Ontiveros Miranda",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2797),
                            Direccion = "Calvo Sotelo, 31 47230 Matapozuelos",
                            Email = "CarpoOntiverosMiranda@dayrep.com",
                            Nombre = "Carpo",
                            Telefono = "783 962 588",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2797)
                        },
                        new
                        {
                            IdLector = 4,
                            Apellidos = "Covarrubias Quiñones",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2800),
                            Direccion = "Cruce Casa de Postas, 3 18420 Lanjarón",
                            Email = "MonserratCovarrubiasQuinones@jourrapide.com",
                            Nombre = "Monserrat ",
                            Telefono = "734 910 062",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2800)
                        },
                        new
                        {
                            IdLector = 5,
                            Apellidos = "Gallardo Suárez",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2802),
                            Direccion = "Camiño Ancho, 43 37765 Monleón",
                            Email = "OmaroGallardoSuarez@dayrep.com",
                            Nombre = "Omaro",
                            Telefono = "748 412 755",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2803)
                        },
                        new
                        {
                            IdLector = 6,
                            Apellidos = "Olivares Escobar",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2806),
                            Direccion = "C/ Hijuela de Lojo, 30 20493 Berrobi",
                            Email = "SaulOlivaresEscobar@jourrapide.com",
                            Nombre = "Saúl",
                            Telefono = "662 479 434",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2807)
                        },
                        new
                        {
                            IdLector = 7,
                            Apellidos = "Barela Méndez",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2808),
                            Direccion = "Bouciña, 25 43780 Gandesa",
                            Email = "TuliaBarelaMendez@rhyta.com",
                            Nombre = "Tulia",
                            Telefono = "681 035 582",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2809)
                        },
                        new
                        {
                            IdLector = 8,
                            Apellidos = "Henríquez Pichardo",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2811),
                            Direccion = "C/ Domingo Beltrán, 54 02250 Abengibre",
                            Email = "NatividadHenriquezPichardo@teleworm.us",
                            Nombre = "Natividad",
                            Telefono = "664 470 154",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2811)
                        },
                        new
                        {
                            IdLector = 9,
                            Apellidos = "Alvarado González",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2813),
                            Direccion = "C/ Señores Curas, 11 12161 la Torre d'En Besora",
                            Email = "NaborAlvaradoGonzalez@dayrep.com",
                            Nombre = "Nabor",
                            Telefono = "633 722 764",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2814)
                        },
                        new
                        {
                            IdLector = 10,
                            Apellidos = "Solórzano Maya",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2815),
                            Direccion = "Rúa Olmos, 5 37330 Babilafuente",
                            Email = "EleodoroSolorzanoMaya@jourrapide.com",
                            Nombre = "Eleodoro",
                            Telefono = "627 022 447",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2816)
                        },
                        new
                        {
                            IdLector = 11,
                            Apellidos = "Toro Robles",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2817),
                            Direccion = "El Roqueo, 28 17230 Palamós",
                            Email = "YrkoToroRobles@dayrep.com",
                            Nombre = "Yrko",
                            Telefono = "775 984 852",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2818)
                        },
                        new
                        {
                            IdLector = 12,
                            Apellidos = "Corral Lara",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2820),
                            Direccion = "Padre Caro, 6 13760 Almuradiel",
                            Email = "EvelienCorralLara@armyspy.com",
                            Nombre = "Evelien",
                            Telefono = "616 556 997",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2821)
                        },
                        new
                        {
                            IdLector = 13,
                            Apellidos = "Ontiveros Vigil",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2823),
                            Direccion = "Escuadro, 57 46841 Castelló de Rugat",
                            Email = "FulgencioOntiverosVigil@teleworm.us",
                            Nombre = "Fulgencio",
                            Telefono = "669 306 461",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2823)
                        },
                        new
                        {
                            IdLector = 14,
                            Apellidos = "Espinosa Ledesma",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2826),
                            Direccion = "Paseo del Atlántico, 76 17500 Ripoll",
                            Email = "FerdinandEspinosaLedesma@teleworm.us",
                            Nombre = "Ferdinand",
                            Telefono = "651 089 265",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2827)
                        },
                        new
                        {
                            IdLector = 15,
                            Apellidos = "Barrientos Sedillo",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2829),
                            Direccion = "Atamaria, 39 36636 Ribadumia",
                            Email = "LupercoBarrientosSedillo@rhyta.com",
                            Nombre = "Luperco",
                            Telefono = "775 279 438",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2830)
                        },
                        new
                        {
                            IdLector = 16,
                            Apellidos = "Hernádez Villegas",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2834),
                            Direccion = "Constitución, 65 37111 Palacios del Arzobispo",
                            Email = "HeldaHernadezVillegas@rhyta.com",
                            Nombre = "Helda",
                            Telefono = "633 662 355",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2835)
                        },
                        new
                        {
                            IdLector = 17,
                            Apellidos = "Arreola Olivares",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2837),
                            Direccion = "C/ Los Herrán, 81 06810 Calamonte",
                            Email = "EliaArreolaOlivares@armyspy.com",
                            Nombre = "Elía",
                            Telefono = "612 597 999",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2838)
                        },
                        new
                        {
                            IdLector = 18,
                            Apellidos = "Vázquez Baca",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2840),
                            Direccion = "Cañadilla, 89 22300 Barbastro",
                            Email = "EneasVazquezBaca@dayrep.com",
                            Nombre = "Eneas",
                            Telefono = "759 793 434",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2841)
                        },
                        new
                        {
                            IdLector = 19,
                            Apellidos = "Rascón Angulo",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2843),
                            Direccion = "C/ Benito Guinea, 92 08330 Premià de Mar",
                            Email = "AbbiRasconAngulo@jourrapide.com",
                            Nombre = "Abbi",
                            Telefono = "674 325 474",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2844)
                        },
                        new
                        {
                            IdLector = 20,
                            Apellidos = "Rivas Espinosa",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2846),
                            Direccion = "Lamas Carbajal, 17 41566 Pedrera",
                            Email = "OrietaRivasEspinosa@jourrapide.com",
                            Nombre = "Orieta",
                            Telefono = "766 258 264",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2846)
                        },
                        new
                        {
                            IdLector = 21,
                            Apellidos = "Banda Alicea",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2849),
                            Direccion = "Camiño Real, 65 48480 Zaratamo",
                            Email = "MariselBandaAlicea@dayrep.com",
                            Nombre = "Marisel",
                            Telefono = "781 296 585",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2849)
                        },
                        new
                        {
                            IdLector = 22,
                            Apellidos = "Zamudio Adame",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2852),
                            Direccion = "Cruce Casa de Postas, 22 18430 Torvizcón",
                            Email = "PrudencianoZamudioAdame@dayrep.com",
                            Nombre = "Prudenciano",
                            Telefono = "722 720 072",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2853)
                        },
                        new
                        {
                            IdLector = 23,
                            Apellidos = "Vasquez Solano",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2855),
                            Direccion = "Atamaria, 2 36780 A Guarda",
                            Email = "AmalioVasquezSolano@dayrep.com",
                            Nombre = "Amalio",
                            Telefono = "722 801 512",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2855)
                        },
                        new
                        {
                            IdLector = 24,
                            Apellidos = "Valverde Elizondo",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2858),
                            Direccion = "Rúa de San Pedro, 79 37795 Berrocal de Salvatierra",
                            Email = "ZahirValverdeElizondo@armyspy.com",
                            Nombre = "Zahir",
                            Telefono = "606 229 390",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2858)
                        },
                        new
                        {
                            IdLector = 25,
                            Apellidos = "Saldana Pulido",
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2860),
                            Direccion = "Carretera del Muelle, 67 12318 Portell de Morella",
                            Email = "LibertoSaldanaPulido@teleworm.us",
                            Nombre = "Liberto",
                            Telefono = "651 019 733",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 207, DateTimeKind.Utc).AddTicks(2861)
                        });
                });

            modelBuilder.Entity("BootstrapDashboard.Models.Libro", b =>
                {
                    b.Property<int>("IdBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBook"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdBook");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("libros");

                    b.HasData(
                        new
                        {
                            IdBook = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4442),
                            Estado = false,
                            ISBN = "978-84-8136-542-9",
                            Nombre = "Una pica en Flandes",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4443)
                        },
                        new
                        {
                            IdBook = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4447),
                            Estado = false,
                            ISBN = "978-84-15313-05-2",
                            Nombre = "Allá ellos",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4448)
                        },
                        new
                        {
                            IdBook = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4450),
                            Estado = false,
                            ISBN = "978-84-15313-59-5",
                            Nombre = "Adiós muchachos",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4451)
                        },
                        new
                        {
                            IdBook = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4454),
                            Estado = false,
                            ISBN = "978-84-7884-546-0",
                            Nombre = "Juguete nuevo",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4455)
                        },
                        new
                        {
                            IdBook = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4458),
                            Estado = true,
                            ISBN = "978-84-16350-14-8",
                            Nombre = "Raúl Sendic",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4458)
                        },
                        new
                        {
                            IdBook = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4461),
                            Estado = true,
                            ISBN = "978-84-7884-500-2",
                            Nombre = "Aquel año en Madrid",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4462)
                        },
                        new
                        {
                            IdBook = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4465),
                            Estado = true,
                            ISBN = "978-956-366-003-6",
                            Nombre = "El último room service",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4466)
                        },
                        new
                        {
                            IdBook = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4468),
                            Estado = false,
                            ISBN = "978-84-8136-572-6",
                            Nombre = "Príapos",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4469)
                        },
                        new
                        {
                            IdBook = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4472),
                            Estado = false,
                            ISBN = "978-84-96546-19-6",
                            Nombre = "LO QUE DURA DURA",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4473)
                        },
                        new
                        {
                            IdBook = 10,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4476),
                            Estado = false,
                            ISBN = "978-84-7884-370-1",
                            Nombre = "De la Habana ha llegado",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4477)
                        },
                        new
                        {
                            IdBook = 11,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4479),
                            Estado = false,
                            ISBN = "978-959-218-103-8",
                            Nombre = "El aguacate y la virtud",
                            UpdatedAt = new DateTime(2023, 9, 5, 20, 55, 33, 200, DateTimeKind.Utc).AddTicks(4480)
                        });
                });

            modelBuilder.Entity("BootstrapDashboard.Models.Libro", b =>
                {
                    b.HasOne("BootstrapDashboard.Models.Genero", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
