// <auto-generated />
using System;
using BootstrapDashboard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BootstrapDashboard.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20230908223712_MigracionPrestamoModelDataSeed2")]
    partial class MigracionPrestamoModelDataSeed2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BootstrapDashboard.Models.Genero", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("CategoryId");

                    b.ToTable("generos");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(5766),
                            Nombre = "Novela Policiaca",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(5769)
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7554),
                            Nombre = "Romántico",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7555)
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7556),
                            Nombre = "Erótico",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7556)
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7557),
                            Nombre = "Ficción",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7558)
                        },
                        new
                        {
                            CategoryId = 5,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7559),
                            Nombre = "Biografía",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7559)
                        },
                        new
                        {
                            CategoryId = 6,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7560),
                            Nombre = "Ensayo",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7561)
                        },
                        new
                        {
                            CategoryId = 7,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7562),
                            Nombre = "Poesía",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7562)
                        },
                        new
                        {
                            CategoryId = 8,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7563),
                            Nombre = "Clásicos Literarios",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7564)
                        },
                        new
                        {
                            CategoryId = 9,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7565),
                            Nombre = "Cómic y Libros Ilustrados",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7565)
                        },
                        new
                        {
                            CategoryId = 10,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7567),
                            Nombre = "Cuentos y Relatos",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7567)
                        },
                        new
                        {
                            CategoryId = 11,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7568),
                            Nombre = "Fantasía",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7569)
                        },
                        new
                        {
                            CategoryId = 12,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7570),
                            Nombre = "Humor",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7570)
                        },
                        new
                        {
                            CategoryId = 13,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7571),
                            Nombre = "Infantil",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7572)
                        },
                        new
                        {
                            CategoryId = 14,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7573),
                            Nombre = "Juvenil",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7573)
                        },
                        new
                        {
                            CategoryId = 15,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7574),
                            Nombre = "Novela Histórica",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7574)
                        },
                        new
                        {
                            CategoryId = 16,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7575),
                            Nombre = "Novela Negra y Policiaca",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7576)
                        },
                        new
                        {
                            CategoryId = 17,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7577),
                            Nombre = "Novela Romántica",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7577)
                        },
                        new
                        {
                            CategoryId = 18,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7578),
                            Nombre = "Terror y Thriller",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7578)
                        },
                        new
                        {
                            CategoryId = 19,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7579),
                            Nombre = "Arte",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7580)
                        },
                        new
                        {
                            CategoryId = 20,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7581),
                            Nombre = "Autoayuda",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7581)
                        },
                        new
                        {
                            CategoryId = 21,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7582),
                            Nombre = "Biografías y Autobiografías",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7582)
                        },
                        new
                        {
                            CategoryId = 22,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7583),
                            Nombre = "Cocina y Gastronomía",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7584)
                        },
                        new
                        {
                            CategoryId = 23,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7585),
                            Nombre = "Deportes",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7585)
                        },
                        new
                        {
                            CategoryId = 24,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7586),
                            Nombre = "Divulgación Científica",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7586)
                        },
                        new
                        {
                            CategoryId = 25,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7587),
                            Nombre = "Enciclopedias y Diccionarios",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7588)
                        },
                        new
                        {
                            CategoryId = 26,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7589),
                            Nombre = "Filosofía",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7589)
                        },
                        new
                        {
                            CategoryId = 27,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7590),
                            Nombre = "Historia",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7591)
                        },
                        new
                        {
                            CategoryId = 28,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7592),
                            Nombre = "Idiomas",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7592)
                        },
                        new
                        {
                            CategoryId = 29,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7593),
                            Nombre = "Libros de Texto",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7594)
                        },
                        new
                        {
                            CategoryId = 30,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7594),
                            Nombre = "Libros Técnicos",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7595)
                        },
                        new
                        {
                            CategoryId = 31,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7596),
                            Nombre = "Madres y Padres",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7596)
                        },
                        new
                        {
                            CategoryId = 32,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7597),
                            Nombre = "Negocios e Inversiones",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7597)
                        },
                        new
                        {
                            CategoryId = 33,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7598),
                            Nombre = "Religión",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7599)
                        },
                        new
                        {
                            CategoryId = 34,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7600),
                            Nombre = "Viajes",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7600)
                        },
                        new
                        {
                            CategoryId = 35,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7601),
                            Nombre = "Teatro y Dramático",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7601)
                        },
                        new
                        {
                            CategoryId = 36,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7602),
                            Nombre = "Lírico",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7603)
                        });
                });

            modelBuilder.Entity("BootstrapDashboard.Models.Lector", b =>
                {
                    b.Property<int>("IdLector")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLector"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdLector");

                    b.ToTable("lector");

                    b.HasData(
                        new
                        {
                            IdLector = 1,
                            Apellidos = "Casanova Almanza",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7765),
                            Direccion = "Ourense, 25 43141 Vilallonga del Camp",
                            Email = "AnaiasCasanovaAlmanza@jourrapide.com",
                            Nombre = "Anaías",
                            Telefono = "783 962 738",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7765)
                        },
                        new
                        {
                            IdLector = 2,
                            Apellidos = "Castro Montoya",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7767),
                            Direccion = "Plaza Colón, 55 26100 Torrecilla en Cameros",
                            Email = "PericlesCastroMontoya@armyspy.com",
                            Nombre = "Pericles",
                            Telefono = "783 962 730",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7767)
                        },
                        new
                        {
                            IdLector = 3,
                            Apellidos = "Ontiveros Miranda",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7769),
                            Direccion = "Calvo Sotelo, 31 47230 Matapozuelos",
                            Email = "CarpoOntiverosMiranda@dayrep.com",
                            Nombre = "Carpo",
                            Telefono = "783 962 588",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7769)
                        },
                        new
                        {
                            IdLector = 4,
                            Apellidos = "Covarrubias Quiñones",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7771),
                            Direccion = "Cruce Casa de Postas, 3 18420 Lanjarón",
                            Email = "MonserratCovarrubiasQuinones@jourrapide.com",
                            Nombre = "Monserrat ",
                            Telefono = "734 910 062",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7771)
                        },
                        new
                        {
                            IdLector = 5,
                            Apellidos = "Gallardo Suárez",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7773),
                            Direccion = "Camiño Ancho, 43 37765 Monleón",
                            Email = "OmaroGallardoSuarez@dayrep.com",
                            Nombre = "Omaro",
                            Telefono = "748 412 755",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7773)
                        },
                        new
                        {
                            IdLector = 6,
                            Apellidos = "Olivares Escobar",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7774),
                            Direccion = "C/ Hijuela de Lojo, 30 20493 Berrobi",
                            Email = "SaulOlivaresEscobar@jourrapide.com",
                            Nombre = "Saúl",
                            Telefono = "662 479 434",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7775)
                        },
                        new
                        {
                            IdLector = 7,
                            Apellidos = "Barela Méndez",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7776),
                            Direccion = "Bouciña, 25 43780 Gandesa",
                            Email = "TuliaBarelaMendez@rhyta.com",
                            Nombre = "Tulia",
                            Telefono = "681 035 582",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7777)
                        },
                        new
                        {
                            IdLector = 8,
                            Apellidos = "Henríquez Pichardo",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7778),
                            Direccion = "C/ Domingo Beltrán, 54 02250 Abengibre",
                            Email = "NatividadHenriquezPichardo@teleworm.us",
                            Nombre = "Natividad",
                            Telefono = "664 470 154",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7778)
                        },
                        new
                        {
                            IdLector = 9,
                            Apellidos = "Alvarado González",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7780),
                            Direccion = "C/ Señores Curas, 11 12161 la Torre d'En Besora",
                            Email = "NaborAlvaradoGonzalez@dayrep.com",
                            Nombre = "Nabor",
                            Telefono = "633 722 764",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7780)
                        },
                        new
                        {
                            IdLector = 10,
                            Apellidos = "Solórzano Maya",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7782),
                            Direccion = "Rúa Olmos, 5 37330 Babilafuente",
                            Email = "EleodoroSolorzanoMaya@jourrapide.com",
                            Nombre = "Eleodoro",
                            Telefono = "627 022 447",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7782)
                        },
                        new
                        {
                            IdLector = 11,
                            Apellidos = "Toro Robles",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7783),
                            Direccion = "El Roqueo, 28 17230 Palamós",
                            Email = "YrkoToroRobles@dayrep.com",
                            Nombre = "Yrko",
                            Telefono = "775 984 852",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7784)
                        },
                        new
                        {
                            IdLector = 12,
                            Apellidos = "Corral Lara",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7785),
                            Direccion = "Padre Caro, 6 13760 Almuradiel",
                            Email = "EvelienCorralLara@armyspy.com",
                            Nombre = "Evelien",
                            Telefono = "616 556 997",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7786)
                        },
                        new
                        {
                            IdLector = 13,
                            Apellidos = "Ontiveros Vigil",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7787),
                            Direccion = "Escuadro, 57 46841 Castelló de Rugat",
                            Email = "FulgencioOntiverosVigil@teleworm.us",
                            Nombre = "Fulgencio",
                            Telefono = "669 306 461",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7787)
                        },
                        new
                        {
                            IdLector = 14,
                            Apellidos = "Espinosa Ledesma",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7789),
                            Direccion = "Paseo del Atlántico, 76 17500 Ripoll",
                            Email = "FerdinandEspinosaLedesma@teleworm.us",
                            Nombre = "Ferdinand",
                            Telefono = "651 089 265",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7789)
                        },
                        new
                        {
                            IdLector = 15,
                            Apellidos = "Barrientos Sedillo",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7791),
                            Direccion = "Atamaria, 39 36636 Ribadumia",
                            Email = "LupercoBarrientosSedillo@rhyta.com",
                            Nombre = "Luperco",
                            Telefono = "775 279 438",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7791)
                        },
                        new
                        {
                            IdLector = 16,
                            Apellidos = "Hernádez Villegas",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7792),
                            Direccion = "Constitución, 65 37111 Palacios del Arzobispo",
                            Email = "HeldaHernadezVillegas@rhyta.com",
                            Nombre = "Helda",
                            Telefono = "633 662 355",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7793)
                        },
                        new
                        {
                            IdLector = 17,
                            Apellidos = "Arreola Olivares",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7794),
                            Direccion = "C/ Los Herrán, 81 06810 Calamonte",
                            Email = "EliaArreolaOlivares@armyspy.com",
                            Nombre = "Elía",
                            Telefono = "612 597 999",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7794)
                        },
                        new
                        {
                            IdLector = 18,
                            Apellidos = "Vázquez Baca",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7796),
                            Direccion = "Cañadilla, 89 22300 Barbastro",
                            Email = "EneasVazquezBaca@dayrep.com",
                            Nombre = "Eneas",
                            Telefono = "759 793 434",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7796)
                        },
                        new
                        {
                            IdLector = 19,
                            Apellidos = "Rascón Angulo",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7797),
                            Direccion = "C/ Benito Guinea, 92 08330 Premià de Mar",
                            Email = "AbbiRasconAngulo@jourrapide.com",
                            Nombre = "Abbi",
                            Telefono = "674 325 474",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7798)
                        },
                        new
                        {
                            IdLector = 20,
                            Apellidos = "Rivas Espinosa",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7799),
                            Direccion = "Lamas Carbajal, 17 41566 Pedrera",
                            Email = "OrietaRivasEspinosa@jourrapide.com",
                            Nombre = "Orieta",
                            Telefono = "766 258 264",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7800)
                        },
                        new
                        {
                            IdLector = 21,
                            Apellidos = "Banda Alicea",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7801),
                            Direccion = "Camiño Real, 65 48480 Zaratamo",
                            Email = "MariselBandaAlicea@dayrep.com",
                            Nombre = "Marisel",
                            Telefono = "781 296 585",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7801)
                        },
                        new
                        {
                            IdLector = 22,
                            Apellidos = "Zamudio Adame",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7803),
                            Direccion = "Cruce Casa de Postas, 22 18430 Torvizcón",
                            Email = "PrudencianoZamudioAdame@dayrep.com",
                            Nombre = "Prudenciano",
                            Telefono = "722 720 072",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7803)
                        },
                        new
                        {
                            IdLector = 23,
                            Apellidos = "Vasquez Solano",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7805),
                            Direccion = "Atamaria, 2 36780 A Guarda",
                            Email = "AmalioVasquezSolano@dayrep.com",
                            Nombre = "Amalio",
                            Telefono = "722 801 512",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7805)
                        },
                        new
                        {
                            IdLector = 24,
                            Apellidos = "Valverde Elizondo",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7848),
                            Direccion = "Rúa de San Pedro, 79 37795 Berrocal de Salvatierra",
                            Email = "ZahirValverdeElizondo@armyspy.com",
                            Nombre = "Zahir",
                            Telefono = "606 229 390",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7848)
                        },
                        new
                        {
                            IdLector = 25,
                            Apellidos = "Saldana Pulido",
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7850),
                            Direccion = "Carretera del Muelle, 67 12318 Portell de Morella",
                            Email = "LibertoSaldanaPulido@teleworm.us",
                            Nombre = "Liberto",
                            Telefono = "651 019 733",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7850)
                        });
                });

            modelBuilder.Entity("BootstrapDashboard.Models.Libro", b =>
                {
                    b.Property<int>("IdBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBook"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdBook");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("libros");

                    b.HasData(
                        new
                        {
                            IdBook = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7722),
                            Estado = false,
                            ISBN = "978-84-8136-542-9",
                            Nombre = "Una pica en Flandes",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7722)
                        },
                        new
                        {
                            IdBook = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7724),
                            Estado = false,
                            ISBN = "978-84-15313-05-2",
                            Nombre = "Allá ellos",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7725)
                        },
                        new
                        {
                            IdBook = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7726),
                            Estado = false,
                            ISBN = "978-84-15313-59-5",
                            Nombre = "Adiós muchachos",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7727)
                        },
                        new
                        {
                            IdBook = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7728),
                            Estado = false,
                            ISBN = "978-84-7884-546-0",
                            Nombre = "Juguete nuevo",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7728)
                        },
                        new
                        {
                            IdBook = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7729),
                            Estado = true,
                            ISBN = "978-84-16350-14-8",
                            Nombre = "Raúl Sendic",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7730)
                        },
                        new
                        {
                            IdBook = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7731),
                            Estado = true,
                            ISBN = "978-84-7884-500-2",
                            Nombre = "Aquel año en Madrid",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7732)
                        },
                        new
                        {
                            IdBook = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7733),
                            Estado = true,
                            ISBN = "978-956-366-003-6",
                            Nombre = "El último room service",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7733)
                        },
                        new
                        {
                            IdBook = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7734),
                            Estado = false,
                            ISBN = "978-84-8136-572-6",
                            Nombre = "Príapos",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7735)
                        },
                        new
                        {
                            IdBook = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7737),
                            Estado = false,
                            ISBN = "978-84-96546-19-6",
                            Nombre = "LO QUE DURA DURA",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7737)
                        },
                        new
                        {
                            IdBook = 10,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7738),
                            Estado = false,
                            ISBN = "978-84-7884-370-1",
                            Nombre = "De la Habana ha llegado",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7739)
                        },
                        new
                        {
                            IdBook = 11,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7740),
                            Estado = false,
                            ISBN = "978-959-218-103-8",
                            Nombre = "El aguacate y la virtud",
                            UpdatedAt = new DateTime(2023, 9, 8, 22, 37, 12, 410, DateTimeKind.Utc).AddTicks(7741)
                        });
                });

            modelBuilder.Entity("BootstrapDashboard.Models.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("LectorId")
                        .HasColumnType("int");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LectorId");

                    b.HasIndex("LibroId");

                    b.ToTable("prestamos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LectorId = 23,
                            LibroId = 5,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LectorId = 19,
                            LibroId = 6,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LectorId = 7,
                            LibroId = 7,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BootstrapDashboard.Models.Libro", b =>
                {
                    b.HasOne("BootstrapDashboard.Models.Genero", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BootstrapDashboard.Models.Prestamo", b =>
                {
                    b.HasOne("BootstrapDashboard.Models.Lector", "Lector")
                        .WithMany()
                        .HasForeignKey("LectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BootstrapDashboard.Models.Libro", "Libro")
                        .WithMany()
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lector");

                    b.Navigation("Libro");
                });
#pragma warning restore 612, 618
        }
    }
}
