// <auto-generated />
using System;
using BootstrapDashboard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BootstrapDashboard.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20230726125936_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BootstrapDashboard.Models.Genero", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("CategoryId");

                    b.ToTable("generos");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 26, 12, 59, 35, 920, DateTimeKind.Utc).AddTicks(9192),
                            Nombre = "Novela Policiaca",
                            UpdatedAt = new DateTime(2023, 7, 26, 12, 59, 35, 920, DateTimeKind.Utc).AddTicks(9195)
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 7, 26, 12, 59, 35, 920, DateTimeKind.Utc).AddTicks(9273),
                            Nombre = "Romántico",
                            UpdatedAt = new DateTime(2023, 7, 26, 12, 59, 35, 920, DateTimeKind.Utc).AddTicks(9274)
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 7, 26, 12, 59, 35, 920, DateTimeKind.Utc).AddTicks(9275),
                            Nombre = "Erótico",
                            UpdatedAt = new DateTime(2023, 7, 26, 12, 59, 35, 920, DateTimeKind.Utc).AddTicks(9275)
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedAt = new DateTime(2023, 7, 26, 12, 59, 35, 920, DateTimeKind.Utc).AddTicks(9276),
                            Nombre = "Ficción",
                            UpdatedAt = new DateTime(2023, 7, 26, 12, 59, 35, 920, DateTimeKind.Utc).AddTicks(9277)
                        },
                        new
                        {
                            CategoryId = 5,
                            CreatedAt = new DateTime(2023, 7, 26, 12, 59, 35, 920, DateTimeKind.Utc).AddTicks(9278),
                            Nombre = "Biografía",
                            UpdatedAt = new DateTime(2023, 7, 26, 12, 59, 35, 920, DateTimeKind.Utc).AddTicks(9278)
                        },
                        new
                        {
                            CategoryId = 6,
                            CreatedAt = new DateTime(2023, 7, 26, 12, 59, 35, 920, DateTimeKind.Utc).AddTicks(9279),
                            Nombre = "Ensayo",
                            UpdatedAt = new DateTime(2023, 7, 26, 12, 59, 35, 920, DateTimeKind.Utc).AddTicks(9279)
                        },
                        new
                        {
                            CategoryId = 7,
                            CreatedAt = new DateTime(2023, 7, 26, 12, 59, 35, 920, DateTimeKind.Utc).AddTicks(9281),
                            Nombre = "Poesía",
                            UpdatedAt = new DateTime(2023, 7, 26, 12, 59, 35, 920, DateTimeKind.Utc).AddTicks(9282)
                        });
                });

            modelBuilder.Entity("BootstrapDashboard.Models.Libro", b =>
                {
                    b.Property<int>("IdBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBook"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdBook");

                    b.HasIndex("CategoryId");

                    b.ToTable("libros");

                    b.HasData(
                        new
                        {
                            IdBook = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 26, 12, 59, 35, 920, DateTimeKind.Utc).AddTicks(9442),
                            Estado = false,
                            ISBN = "978-84-8136-542-9",
                            Nombre = "Una pica en Flandes",
                            UpdatedAt = new DateTime(2023, 7, 26, 12, 59, 35, 920, DateTimeKind.Utc).AddTicks(9442)
                        });
                });

            modelBuilder.Entity("BootstrapDashboard.Models.Libro", b =>
                {
                    b.HasOne("BootstrapDashboard.Models.Genero", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
