// <auto-generated />
using System;
using BootstrapDashboard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BootstrapDashboard.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20230725011051_MigracionInicialDBSeedingGenero")]
    partial class MigracionInicialDBSeedingGenero
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BootstrapDashboard.Models.Genero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GeneroId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("generos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3eeb4c70-7b00-4100-a614-06b1226aad4d"),
                            CreatedAt = new DateTime(2023, 7, 25, 1, 10, 51, 517, DateTimeKind.Utc).AddTicks(7684),
                            Nombre = "Novela Policiaca",
                            UpdatedAt = new DateTime(2023, 7, 25, 1, 10, 51, 517, DateTimeKind.Utc).AddTicks(7689)
                        },
                        new
                        {
                            Id = new Guid("d805f947-3067-4c43-b9a7-61242a494147"),
                            CreatedAt = new DateTime(2023, 7, 25, 1, 10, 51, 517, DateTimeKind.Utc).AddTicks(7691),
                            Nombre = "Romántico",
                            UpdatedAt = new DateTime(2023, 7, 25, 1, 10, 51, 517, DateTimeKind.Utc).AddTicks(7692)
                        },
                        new
                        {
                            Id = new Guid("d365c33d-97bd-47f9-8dfc-c3b0c419601e"),
                            CreatedAt = new DateTime(2023, 7, 25, 1, 10, 51, 517, DateTimeKind.Utc).AddTicks(7694),
                            Nombre = "Erótico",
                            UpdatedAt = new DateTime(2023, 7, 25, 1, 10, 51, 517, DateTimeKind.Utc).AddTicks(7694)
                        },
                        new
                        {
                            Id = new Guid("55032df2-d022-4366-8c71-eb1edb0e1afd"),
                            CreatedAt = new DateTime(2023, 7, 25, 1, 10, 51, 517, DateTimeKind.Utc).AddTicks(7696),
                            Nombre = "Ficción",
                            UpdatedAt = new DateTime(2023, 7, 25, 1, 10, 51, 517, DateTimeKind.Utc).AddTicks(7697)
                        },
                        new
                        {
                            Id = new Guid("66490248-4be0-4e75-aea5-ebad4543da34"),
                            CreatedAt = new DateTime(2023, 7, 25, 1, 10, 51, 517, DateTimeKind.Utc).AddTicks(7698),
                            Nombre = "Biografía",
                            UpdatedAt = new DateTime(2023, 7, 25, 1, 10, 51, 517, DateTimeKind.Utc).AddTicks(7699)
                        },
                        new
                        {
                            Id = new Guid("738977c7-68ab-4874-a3fa-67938165ea55"),
                            CreatedAt = new DateTime(2023, 7, 25, 1, 10, 51, 517, DateTimeKind.Utc).AddTicks(7710),
                            Nombre = "Ensayo",
                            UpdatedAt = new DateTime(2023, 7, 25, 1, 10, 51, 517, DateTimeKind.Utc).AddTicks(7710)
                        },
                        new
                        {
                            Id = new Guid("621effe3-ff0f-4fce-8fe0-17c50225242e"),
                            CreatedAt = new DateTime(2023, 7, 25, 1, 10, 51, 517, DateTimeKind.Utc).AddTicks(7712),
                            Nombre = "Poesía",
                            UpdatedAt = new DateTime(2023, 7, 25, 1, 10, 51, 517, DateTimeKind.Utc).AddTicks(7712)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
